name: tips_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  calendar_date_picker2: ^1.1.7
  provider: ^6.0.0  # Asegúrate de que esté en la última versión
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"

flutter:
  uses-material-design: true
